// description des lignées vampiriques ==========================

class History {
    constructor(description){ 
        this.description =  description;
    }
};

const assamiteHy = new History ("Les Assamites sont des tueurs fanatiques vénérés par toutes les guildes d'assassin dont ils sont l'élite suprême et secrète. Ils ont en charge la protection du sanctuaire et de Maitre Agot. Et nul ne souhaite se mettre à dos cette terrible confrérie.Tuer est pour eux un art et chaque contrat est honoré comme un rituel sacré. Le meurtre est méthodiquement préparé, organisé en fonction de la victime de façon à faire de l'acte finale un châtiment divin. Un assamite ne peut échouer aucun contrat, sous peine d'être mis à mort par les siens, ce qui fait que quel que soit l'enjeu, le contrat sera rempli, question d'honneur et de survie ! ");
const necromancienHy = new History ("Les Nécromanciens sont des sorciers puissants qui passent leur nuit à l'étude de la magie. L'apprentissage  est long mais qu'importe, ils ont l'éternité devant eux. De plus, ils ont développé leur propre magie : les sortilèges vampiriques. Ces sorts biens  particuliers  ne peuvent être utilisé que part les vampires et ne sont connus que des nécromanciens.  Les nécromanciens se préoccupent peu des histoires entre les hommes mais restent prêt à tout pour l'acquisition d'un vieux grimoire de magie ou de la connaissance de nouveaux sorts. Ils étudient, dissèquent des spécimens et mènent des expériences dans leur atelier.  Les nécromanciens sont souvent les chefs de convent ou les conseillers de prince vampirique. Ceux sont également de grands stratèges politiques.")
const chaosHy = new History ("Les Seigneurs du chaos sont des guerriers vampires nés des grands troubles de l'histoire. Ils sont généralement natifs des Royaumes Glacés du Nord ou des Terres de Malédictions. Ce sont des Chaotiques qui ne vivent que pour la guerre, le carnage, la destruction. Les champs de bataille sont leurs lieux de repos, ils se sustentent de leurs ennemis vaincus et prient tous les dieux chaotiques dont ils estiment être les  représentant sur terre. Ces vampires ne suivent qu'une logique : la leur. Ils sont les plus forts et aiment à le montrer constamment. Ils prennent part à toutes les guerres, les conflits. S'il n'y en a pas,  ils la déclenchent, la provoquent, lèvent une armée et la font. Peu importe quoi et comment ! De toute façon ils la gagneront. Devenir un seigneurs du chaos est le plus grand privilège pour un soldat ou un guerrier de l'armée chaotique. Il devient alors chef de guerre et meneur de la troupe. Les Seigneurs de Chaos sont les plus grands maitres de guerre de tous les âges. Une fois élu, le SdC reçoit la marque de Khorne et peut descendre aux forges d'Arkhar pour y forger son armure maudite. Une armure du chaos est une entité vivante, ancré dans les chairs de son maitre, une seconde peau de métal qui ne peut pas être retiré. Par conséquent, le SdC n'use pas du pouvoir de transformation. Il ne s'abaisse pas à reprendre forme humaine ou se transformer en gargouille. Néanmoins, il utilise à sa manière les pouvoirs du spectre. ( voir pouvoir )");
const sethisteHy = new History ("Les Sethistes sont des manipulateurs et la corruption incarnés. Ils tirent des ténèbres leurs pouvoirs psychiques prompt à corrompre les âmes. Ces vampires sont passés maître de la traîtrise et du complotage. Ils tissent des intrigues et y font tombés leurs victimes. Manipulateurs sournois ils n'ont d'autres objectifs de gangrener les civilisations, corrompre les ordres religieux et pousser les individus vers le côté sombre de leur âme. Il n'est par rare de les trouver comme conseiller auprès des maitres de convent ou introduit à la cour de certains royaume. Les sethistes sont aussi à l'aise sous forme vampirique que sous forme humaine. Ils sont à ce jour les seuls vampires capable d'user de leur pouvoir de lignée sous forme humaine, ce qui leur confère un avantage extrême. ");
const enfantNuitHy = new History ("Les Enfants de la nuit sont les ombres qui hantent les cités à la tombée du jour. Maître de la discrétion et de la dissimulation, ils se faufilent sur les toits, escaladent les tours, crochètent portes et fenêtres pour s'introduire dans les riches demeures ou les bastions fortifiés. Les membres de ce clan mettent un point d'honneur à s'infiltrer dans les endroits les plus inaccessibles et dérober les trésors les plus précieux. La nuit est leur territoire, le vent les portent par-delà les villes et les bons bourgeois  craignent pour leur or ...");

// export ===========================

export { assamiteHy, necromancienHy, chaosHy, sethisteHy, enfantNuitHy  };